package com.bit.utsav;

/**
 * Created by PC on 3/17/2016.
 */
public class Rules {
    public static final String painting ="IT SHOULD BE IN THE PRESCRIBED TOPIC. THE COLOR COMPOSITION AND COMBINATION, SKILLED EXPRESSIONS, PECULIARITY OF LINES, PERFECTION ARE EVALUATED. \n" +
            "CONDITIONS FOR EVALUATION\n" +
            "1.\tPROPRIETY OF COLORS\n" +
            "2.\tSUITABILITY WITH EACH OTHER\n" +
            "3.\tATTRACTION\n" +
            "4.\tCOLOR COMPOSITION\n" +
            "5.\tIMAGINATION\n";
    public static final String pencil="•\t1 PERSON \n" +
            "•\tDURATION : 1 HOUR\n" +
            "•\tTOPIC: ON THE SPOT \n" +
            "•\tMATERIALS WILL NOT BE GIVEN EXCEPT PAPER\n";
    public static final String singing="SOLO" +
            "•\tDURATION: 5 MINUTES \n" +
            "•\tEASTERN/ WESTERN \n" +
            "•\tNO RESTRICTION FOR LANGUAGE \n" +
            "\nGROUP" +
            "•\tDURATION: 5 MINUTES \n" +
            "•\tMAXIMUM 6 MEMBERS AND MIN 2 MEMBER IN A GROUP \n" +
            "•\tANY LANGUAGE\n";
    public static final String dance="o\tDURATION : 7 MINUTES\n" +
            "o\tMAXIMUM 6 MEMBERS IN A GROUP \n" +
            "o\tMINIMUM 3 MEMBERS IN A GROUP\n" +
            "o\tCLASSICAL/ SEMI-CLASSICAL /FOLK/FILM DANCE\n" +
            "o\tCOSTUME MATTERS\n";
    public static final String mono="CLARITY OF PRONUNCIATION AND IDEA, ACTIONS WHICH EXPRESSES REALITY, CONVERSATION AND VALUE OF THE CONTENT, CHARACTERIZATION ARE EVALUATED. PARTICIPANT CAN PRESENT ABOUT AN EVENT OR A PART OF IT OR A CHARACTER OF IT. SUITABLE DRESSING IS DESIRED. NO BACK GROUND MUSIC AND PLAY BACK ASSISTANCE ARE ALLOWED.\n" +
            "\n" +
            "CONDITIONS FOR EVALUATION\n" +
            "1.\tCLARITY OF IDEA, VALUE OF CONTENT.\n" +
            "2.\tBEAUTIFUL PRESENTATION\n" +
            "3.\tTIMING\n" +
            "4.\tACTION\n" +
            "5.\tCONVERSATION \n";
    public static final String dumbchardes ="SPEECH IS SILVER, SILENCE IS GOLD. IT’S TIME FOR ACTION, WORDS ARE OLD !\n" +
            "• HINDI DUMB CHARADES\n" +
            "• EVERY TEAM WILL HAVE 3 MEMBERS\n" +
            "• THE EVENT WILL BE ORGANIZED FOR ONLY MOVIE TITLES (TIME LIMIT : 2 MINUTES) \n" +
            "• EACH MEMBER OF THE TEAM HAS TO COME AT LEAST ONCE FOR GESTICULATION\n" +
            "• LIP MOVEMENT OR ANY KIND OF SOUND IS NOT ACCEPTABLE.\n" +
            "• ANY WORD TO BE GUESSED SHOULD NOT BE DIRECTLY POINTED OUT TO OTHER TEAM MEMBERS.\n" +
            "• ANY WORD CAN BE BROKEN INTO MAXIMUM OF TWO PARTS.\n" +
            "• IN CASE OF ANY DISCREPANCIES, THE DECISION OF JUDGES WILL BE FINAL AND BINDING.\n";
    public static final String photo="• PARTICIPANTS ARE REQUIRED TO SUBMIT A SET OF SIX PHOTOGRAPHS WHICH WILL BE DISPLAYED AS A PANEL\n" +
            "• MINIMUM SIZE OF A PHOTOGRAPH SHOULD BE 6” × 8”\n" +
            "• TOPICS :PROSPECTIVE\n";

    public static final String picknspeak="•\tMONOLOGUE SHOULD BE SELECTED FROM THE LOT AND PERFORMED.\n" +
            "•\tEVERY TEAM WILL HAVE 2 MEMBERS\n" +
            "•\tSTUDENT SHOULD IDENTIFY THEIR SELECTION BEFORE THEY BEGIN THEIR PRESENTATION.\n" +
            "•\tTIME LIMITS FOR THE PRESENTATION ARE 5 MINUTES.\n" +
            "•\tPROMPTING IS ALLOWED. IF STUDENTS REQUIRE PROMPTING, THEY MUST SAY \"LINE.\"\n" +
            "•\tTHE DECISION OF THE JUDGES WILL BE FINAL.\n";

    public static final String clay="JUDGING CRITERIA:\n" +
            "•\tCREATIVITY\n" +
            "•\tORIGINALITY\n" +
            "•\tREFINEMENT\n" +
            "•\tAESTHETICS\n" +
            "•\tCOMMUNICATION ASPECT.\n" +
            "RULES & REGULATIONS:\n" +
            "•\tOIL & CLAY IS TO BE BROUGHT BY THE PARTICIPANTS.\n" +
            "•\tTHEME OR TOPIC WILL BE GIVEN ON THE SPOT.\n" +
            "•\tMODEL SHOULD DEPICT THE THEME OR TOPIC.\n" +
            "•\tDURATION OF 2 HOURS AND 30 MINUTES.\n" +
            "•\tNO OF PARTICIPANTS - GROUP OF TWO.\n" +
            "•\tEACH MODEL HAS TO BE ACCOMPANIED WITH A SHORT WRITE UP ABOUT THE INTERPRETATION OF THE THEME.\n" +
            "•\tTHE DECISION OF THE JUDGES WILL BE FINAL.\n";

    public static final String debate="1.\tEACH TEAM CONSISTS OF TWO MEMBERS\n" +
            "2.\tEACH TEAM WILL GET 2 MINUTES TO PREPARE AFTER THEY RECEIVE THE TOPIC\n" +
            "3.\tTHE FIRST TEAM GETS 5 MINUTES TO SPEAK ON THEIR TOPIC, MEANWHILE OPPONENT TEAM SHOULDN’T INTERRUPT DURING THIS PERIOD\n" +
            "4.\tAFTER THIS PERIOD THERE WILL BE COUNTER ARGUMENT SESSION BETWEEN 2 TEAMS FOR 5 MIN\n" +
            "5.\tNEXT THERE WILL BE QUESTION ANSWERS SESSION BY JUDGES AND AUDIENCES\n";
    public static final String quiz="TWO PARTICIPANTS IN A TEAM\n" +
            "ROUND 1: ELIMINATION ROUND(MULTIPLE CHOICE)\n" +
            "ROUND 2: QUALIFYING ROUND\n" +
            "ROUND 3:STAGE ROUND\n";
    public static final String movie="1.\tMAXIMUM 8 MEMBERS IN A TEAM\n" +
            "2.\tTIME LIMIT :MAXIMUM 15 MINUTES\n" +
            "3.\tNO LANGUAGE RESTRICTIONS. ENGLISH SUBTITLES ARE COMPULSORY REQUIRED FOR LANGUAGES OTHER THAN ENGLISH\n" +
            "4.\tDISCLAIMER HAS TO BE MENTIONED(SMOKING IS INJURIOUS TO HEALTH)\n" +
            "5.\tPARTICIPANTS SHOULD REGISTER THEIR NAMES WITH CO COORDINATORS\n" +
            "6.\tDECISION OF THE JUDGES WILL BE FINAL\n" +
            "7.\tMOVIE WITH A MORAL MESSAGE(SOCIAL RESPONSIBLITIES) WILL CARRY MORE VALUE\n";
    public static final String face="1.\tTWO PATRTICIPANTSIN  A TEAM.\n" +
            "2.\tPARTICIPANTS SHOULD BRING THEIR OWN COLOURS, BRUSHES ETC.\n" +
            "3.\tTIME DURATION IS 60 MINS.\n" +
            "4.\tTOPIC WILL BE GIVEN ON THE SPOT.\n" +
            "5.\tPARTICIPANTS WILL BE JUDGED ON THIER CREATIVITY, INNOVATION AND DESIGN.\n" +
            "6.\tDECISION OF THE JUDGES WILL BE FINAL.\n";
    public static final String mime="1.\tMAXIMUM 8 MEMBERS IN A TEAM.\n" +
            "2.\tTIME  LIMIT 5 MINS.\n" +
            "3.\tNEGATIVE POINTS FOR EXCEEDING TIME LIMIT.\n" +
            "4.\tTHE ACT SHOULD NOT CONTAIN ANY DIALOGUES, LIP SYNCING OR PROPS.\n" +
            "5.\tNO ACT SHOULD CONTAIN ANY OFFENSIVE, OBSCENE, DISRESPECTFUL ACTIONS OR GESTURES.THE ACT WILL BE IMMEDIATELY STOPPED AND THE ENTRY WILL BE DISQUALIFIED,IF THESE INSTRUCTIONS ARE NOT FOLLOWED.\n" +
            "6.\tPOINTS WILL BE GIVEN ON THE BASIS OF INNOVATION, DEPICTION OF THE SITUATION, TEAM WORK AND EXPRESSIONS.\n" +
            "7.\tDECISION OF THE JUDGES WILL BE FINAL.\n";
    public static final String selfie="1.\tMINIMUM 2 AND MAXIMUM 5 PARTICIPANTS IN A TEAM.\n" +
            "2.\tONLY CELLPHONES OR TABLETS ARE ALLOWED.\n" +
            "3.\tTHE DEVICE SHOULD HAVE SHARING APPLICATIONS LIKE SHAREIT ,XENDER.\n" +
            "4.\tSELFIE STICK IS PERMITTED.\n" +
            "5.\tGROUP SHOULD PERFORM 10 GIVEN TASKS WITHIN SPECIFIED TIME.\n" +
            "6.\tWINNERS WILL BE AWARDED WITH EXITING GIFTS.\n";
    public static final String collage ="EXPRESS AN IDEA WHICH EXPLAINS THE SUBJECT GIVEN WITH THE USE OF PAPER CUTTINGS, PHOTOS, CLOTHS, RIBBON ETC. ONLY WATER COLORS ARE ALLOWED FOR NEEDED DESCRIPTION (MINIMUM DESCRIPTION IS ALLOWED). THE TOPIC WILL BE GIVEN IN ADVANCE. THE PAPER ON WHICH THE COLLAGE SHOULD BE MADE WILL BE DISTRIBUTED BY THE FESTIVAL COMMITTEE ON THE FIRST DAY OF THE EVENT (10 AM, 18TH OCT). IT SHOULD BE SUBMITTED IN THE COUNTER ON THE SAME DAY NIGHT (9 PM, 18TH OCT). A STATE TEAM OF STUDENTS CAN BE PERFORMED. NO SPECIAL CONTESTANT WILL BE ACCOMMODATED.\n" +
            "\n" +
            "CONDITIONS FOR EVALUATION\n" +
            "1.\tCREATIVITY AND IMAGINATION\n" +
            "2.\tDIVERSITY OF COLLECTION\n" +
            "3.\tCLARITY OF THEME AND CONTENT\n" +
            "4.\tATTRACTION\n" +
            "5.\tINNOVATIVE IDEAS\n";

    public static final String skit="•\tMAXIMUM PARTICIPANTS: 8 MEMBERS\n" +
            "•\tTIME LIMIT: 20 MINUTES\n" +
            "•\tMAXIMUM 10 MINUTES WILL BE ALLOWED FOR STAGE ARRANGEMENTS.\n" +
            "•\tPLOT OF THE STORY, MATCH OF THE ACTIONS, PRESENTATION, DIRECTION, CONVERSATION, DRESSING ETC WILL BE EVALUATED.\n" +
            "•\tSCRIPT WRITTEN BY THE STUDENTS THEMSELVES IS PREFERRED. \n" +
            "•\tTHE PLAY BACK ASSISTANTS SHOULD BE STUDENTS.\n" +
            "•\tONE ACT PLAY IS PREFERRED. \n" +
            "•\tARRANGEMENT OF STAGE AND FURNITURE, CONTROLLING THE BACK CURTAIN AND ARE AT THE TEAM’S RISK.\n" +
            "•\tBACK GROUND SOUNDS CAN BE PLAYED.\n" +
            "CONDITIONS FOR EVALUATION\n" +
            "1.\tMORAL CHARACTER OF THE SUBJECT\n" +
            "2.\tACTION \n" +
            "3.\tDRESSING AND CONVERSATION\n" +
            "4.\tPRESENTATION, DIRECTION, DRAMATIC MANNER\n" +
            "5.\tCLIMAX\n";
    public static final String minimilitia="\uF076\t4 PLAYERS PER TEAM.\n" +
            "\uF076\tPLAYERS REQUESTED TO GET THEIR SMART PHONES WITH MINIMILITIA.\n" +
            "\uF076\tNO PURCHASED ITEMS TO BE USED.\n" +
            "\uF076\tONE MEMBER FROM EACH TEAM IS REQUIRED TO TAKE THE SCREENSHOT OF THE POINT TABLE, IF FAILED COORDINATES DECISION IS FINAL.\n" +
            "\uF076\tONE PERSON CAN PLAY ONLY IN ONE TEAM.\n" +
            "\uF076\tGAME WILL BE CONDUCTED ON KNOCKOUT BASIS.\n" +
            "\uF076\tREGISTRATION FEES : RS. 40/-\n";
    public static final String madads="BRING OUT THE CREATIVITY INSIDE YOU & MAKE AN OUTSTANDING ADVERTISEMENT OF YOUR OWN. BE IT HILARIOUS OR SENSITIVE, BE IT JUST YOUR CREATIVITY & AD SENSE.\n" +
            "RULES :\n" +
            "\uF076\tEACH TEAM SHOULD HAVE 4-5 MEMBERS.\n" +
            "\uF076\tTOPICS WOULD BE PROVIDED ON THE SPOT.\n" +
            "\uF076\t5 MINUTES PREPARATION TIME FOR EACH TEAM.\n" +
            "\uF076\tTIME LIMIT FOR AD IS 1-2 MINUTES.\n" +
            "\uF076\tPARTICIPANTS SHALL BE JUDGED ON THE BASIS OF SPONTANEITY, CONTENT, ADHERENCE TO THE TOPIC, ON STAGE PRESENTATION, CO-ORDINATION AND OVERALL APPEAL OF THE ADVERTISEMENT.\n" +
            "\uF076\tTHE CAUTION SHOULD BE TAKEN TO REFRAIN FROM DISPLAYING OBSCENITY, VIOLENCE, PREJUDICE, DEFAMATION ETC. IN AD.\n" +
            "\uF076\tDECISION OF THE JUDGES WILL BE FINAL & BINDING.\n";
    public static final String mehendi="RULES :\n"+
            "\uF076\tTIMING : 1HOUR\n"+
            "\uF076\tALL THE PARTICIPANTS SHOULD GET THE MEHANDI CONE.\n"+
            "\uF076\tDESIGN : MUST BE INDIAN & ARABIC.\n"+
            "\uF076\tPARTICIPANTS WILL BE DISQUALIFIED IF FOUND USING MOBILE PHONE OR ANY KIND OF MATERIALS TO COPY THE DESIGN.\n";

    public static final String cook="RULES :\n" +
            "\uF076\t6 MEMBERS IN A TEAM.\n" +
            "\uF076\tTEAM SHOULD HAVE A UNIQUE IDENTIFICATION.\n" +
            "\uF076\tTIME LIMIT : 1:30 HOURS\n" +
            "\uF076\tEACH TEAM SHOULD PREPARE A STARTER, MAIN COURSE & A DESSERT.\n" +
            "\uF076\tNO SHARING OF STUFFS WITH OTHER TEAMS.\n" +
            "\uF076\tPROCEDURE OF COOKING SHOULD BE EXPLAINED DURING JUDGMENT.\n" +
            "\uF076\tINNOVATION, PRESENTATION & TASTE MATTERS DURING JUDGMENT.\n" +
            "\uF076\tBASIC CHOPPING IS ALLOWED, CRAVINGS MUST BE DONE FROM SPOT.\n";
    public static final String treasur="RULES :\n" +
            "\uF076\t4 MEMBERS(SAME BRANCH) PER TEAM.\n" +
            "\uF076\tMISBEHAVING TEAM WILL BE DISQUALIFIED.\n" +
            "\uF076\tTHE CLUES ARE TO FOUND IN A PARTICULAR ORDER & A TEAM CANNOT SKIP ANY CLUE.\n" +
            "\uF076\tENTIRE TEAM MUST STAY TOGETHER.\n" +
            "REGISTRATION FEES : RS.40/-(PER TEAM)\n";
    public static final String cs="RULES :\n" +
            "\uF076\tONE PERSON CAN PLAY IN ONLY ONE TEAM.\n" +
            "\uF076\tEACH ROUND OF 3 MINUTES. FOR EACH MATCH, TOTAL OF 12 ROUNDS. FIRST TEAM TO WIN 7 ROUNDS WILL BE THE WINNER.\n" +
            "\uF076\tFINAL WILL BE OF 22 ROUNDS. DECISION WILL BE MADE BY 1 KNIFE ROUND, WHO WINS WILL GET TO DECIDE THE TEAM. FIRST ONE TO WIN 13 ROUNDS WILL BE DECLARED AS THE WINNER.\n" +
            "\uF076\tIF BOTH TEAM WIN EQUAL TIMES, ADDITIONAL 3 ROUNDS WILL BE CONDUCTED, A KNIFE ROUND IS CONDUCTED. THE TEAM WHICH WINS WILL GET TO CHOOSE CT OR T.\n" +
            "\uF076\tAUTOMATIC SNIPER FOR TERRORISTS & TACTIC SHIELD FOR CT ARE BANNED.\n" +
            "\uF076\tIF ANY RULES ARE VIOLATED THE TEAMS WILL BE DISQUALIFIED.\n" +
            "\uF076\t REGISTRATION FEE : RS. 50/-\n";
    public static final String selfieVideo="Topic: Why i like BIT\n" +
            "Video should be submitted before 28th\n" +
            "Time Limit: 1 minute ";


}
